name: Making memories
favicon: null
layout_spectrum: 1
typography_spectrum: 0.62711
title: Trouwfotografie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#dbdbdb'
    - '#050505'
    - '#a3a3a3'
    - '#4a4a4a'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
