name: Making memories
favicon: null
layout_spectrum: 0.17938865162432194
typography_spectrum: 0.9978383067063987
title: Trouwfotografie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4570296034216881
  lightness: 0.33143396442756057
  saturation: 0.18151533440686762
  rhythmicContrast: 0.7021390667650849
purpose: []
